language: node_js
node_js:
- '8'
sudo: false
branches:
  only:
  - master
os:
- linux
install:
- yarn install
script:
- yarn test --silent
deploy:
  provider: npm
  email: dev@xcomponent.com
  skip_cleanup: true
  api_key:
    secure: dajqLCZzFOAf3QZ2ZLF5ontjaduVzFJN2SjP0SK+aGiIHq7G+kWg1shj6stAzh17xUMl7K1L8xn16zKMT3zM9KTt30KpByoUJwVKEuvHdEaY5y3n8PtRx9YUoNotOscu1p1gx4raEfJY8gtfeyA0RS/n1oQPE3YPW9J/Vx9UOJkXdynEECmP7Onzsz1/GS4SfZCS/gt58dOp9hcIpOiSqs9H5fh8R0SvMHa1cfh6JAYt46pJZZClXvrpzMeZ/Hg2p4dWmoVREe5E3MtRw+JQfS5kFbi9JYH8NTNiAwOPiaknUlidXLaLvLzlOQOy0f8u5R8m9IZApRxDLcHTGMVYsPsxscL0fEwT8G2/r6EZqVQDtDxAoZZQg7+/nuvejSVtcnU8P6lU+T44ljGn6dkHZcrnNOY9co8Lk2wYJd6pI60DgMICDzMk937s7eSmOADM1RMjQ59D8EfNDj4+Xd8fFy4hbTeNZMttsCQ1ViqD4cKWsJ257zoimllSNBVnTg3tgmZLJzlyYCAZ6dAw/+7kwgT40qUhjmwkFyWHyOiAyDGQu9faL4U+6JprtZZuuUlOb7wRaRFSGorsSIhX1hdc1LRClWsV/IXV7ppvg75CWZSF1QA/SGZYn/LTYZ+zyawUFcf+yA53FI5dX9hSoYv4FPLrDMW4jOQaXOh3q6XbMj0=
  on:
    branch: master
    condition: "`bash ./checkTag.sh` = OK"
notifications:
  slack:
    secure: WL4G9ndyWEvkZl5njQF8gReRsbczVPEFI0KjNv4Z51iKoOb2M+VHsO75TRf1luBbG9c8971aV15uLIyMzzheOVtMCkeezarnu/YjdOizSBO4AtQooAar2rmcVD6yVuSESDuxv+faI7Y/NM6ORMnd3eul96yJNyS9mtsYblr898ZwN1eFJrYeYFWiObZWHKZjSx6CCRewqwNlHwfR8sG+gn+0XjvN7h4YK5re978fRVp6lWZ9E9PFy0NXuPUB1YrlQBrBqRAqj6gV28AUbAbTFYrQwmf4ygLgCUgxoW4JHfHqJvTVXYtcGXa/WtrwtApvpMKGE2WAmNl5jvRaBtMxfJH4zR/6UoNO9N8oNlqic2YpT4XdpYjOM2ne2IuE1ES/auKfkk/jU9XLQ82ORl3CeSpGFEfi8jQdp1MljmmU3eq42XWbN2mba+D4VJ/yVBKa1KmQNDkRDAdN01FJawQF1GDv+lQiEaBRjUifATe+9jl/iggWZecHvbz6fzVuETwlxgn68+UqhIdmC0ggOvuSjelKa0RJ8+b+JubJnWZfLK21ZHhOunaAGRv4FBTBLmjOlL4kSS+K2L1Bq6y19R7EC9ubPv6owK37Z2Q5qMWkHyqZ+iep3dPnRhgjKnJ8tfxAkknbpczJwKnyziJ5MzJT5FqPdjSp8SfI8B4zB0tbfBY=
